version: '3.8'
services:
  db:
    image: mariadb:10
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_study
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always
